name: Build Windows EXE for QFTCalc

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install matplotlib

    - name: Generate .spec file
      run: pyinstaller --name QFTCalc --onefile QFTCalc.py

    - name: Rebuild using spec (handles matplotlib data files)
      run: pyinstaller QFTCalc.spec

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: QFTCalc-windows-exe
        path: dist/QFTCalc.exe
